### ISSUE TITLE
Preview doesn't display Bold Text

### ISSUE THREAD

**Issue by JhongHawan** [placeholder-team-name/placeholder#11]
Prior to save and preview: 
![Postcards Prior to Save](https://user-images.githubusercontent.com/37948158/59242665-43907380-8bc1-11e9-9868-930101be7e17.PNG)

After save and preview:
![Postcards After Save](https://user-images.githubusercontent.com/37948158/59242699-6ae74080-8bc1-11e9-8152-c50ff95c206a.PNG)

Steps to recreate:

1.) Type some text.
2.) Save 
3.) Bold the text.
4.) Save
5.) Preview

**Comment by kwokwilliam** [comment]
Fixed already, https://github.com/placeholder-team-name/postcards/commit/ce36299a961f6d3cc0e3756a91d4038208799ae3
