### ISSUE TITLE
Login/Signup 

### ISSUE THREAD

**Issue by yiranni** [placeholder-team-name/placeholder#12]
Login/Signup takes me to use my Google account, but not sure this makes me log in or sign up. It might be better if you provide two options- both sign up and log in. For users with accounts created, they can directly sign up on the site rather than direct them to google account again.

**Comment by yiranni** [comment]
Login/Signup takes me to use my Google account, but not sure this makes me log in or sign up. It might be better if you provide two options- both sign up and log in. For users with accounts created, they can directly sign up on the site rather than direct them to google account again.

**Comment by kwokwilliam** [comment]
To fix: Change what button says to "log in with google" or something to make it more clear

**Comment by kwokwilliam** [comment]
This is not a real failure, however according to this request we made modifications. Changed to log in with google. Reflected in commit: https://github.com/placeholder-team-name/postcards/commit/f3f0b01964013cd1e0f6d734abe5ab6e1fb640d2
