### ISSUE TITLE
Feedbacks on "send"

### ISSUE THREAD

**Issue by yiranni** [placeholder-team-name/placeholder#13]
- When clicking "send", it would be better if there is feedback given, which tells me whether this postcard was sent or not. Maybe you can have a popup window or texts saying something like "Postcard sent". 
- It would be better to show the receiver somewhere on this page.

**Comment by kwokwilliam** [comment]
It says postcards sent, so we are all unsure what was the issue there, and were unable to replicate the issue.

Showing receivers is not part of our requirements but we will get to it if we have time.

**Comment by clairehjk** [comment]
Resolved. We decided to replace the button with a "Sending..." feedback and redirect users to a Sent confirmation page.
