### ISSUE TITLE
After I've sent the postcard the text entry box does not clear my last message. 

### ISSUE THREAD

**Issue by summerjoyyoung** [placeholder-team-name/placeholder#15]
After I've sent the postcard the text entry box does not clear my last message. 

Steps:
1.) Logged/signed up with google account
2) clicked on recipients
3) added my info to the recipients
4) clicked on the home postcard logo to go back to the write postcard page
5) wrote a message
6) clicked the save button
7) clicked the preview button
8) clicked the send button

The sent feedback is shown

9) I click the write button to send a new message

after this, the previous message still shows in the edit text box.
![image](https://user-images.githubusercontent.com/26681019/59244053-c0265080-8bc7-11e9-9acf-ad6386b64f7b.png)
![image](https://user-images.githubusercontent.com/26681019/59244069-cae0e580-8bc7-11e9-8cb8-94eefcb83599.png)

**Comment by kwokwilliam** [comment]
Intentional behavior because these are to be monthly postcards
