### ISSUE TITLE
After click safe, the layout will disappear in text editor

### ISSUE THREAD

**Issue by s21dy** [placeholder-team-name/placeholder#16]
- I have three sentence if the text editor
![Screen Shot 2019-06-10 at 9 43 05 PM](https://user-images.githubusercontent.com/43624825/59244320-c36e0c00-8bc8-11e9-9e41-6fceb7ab1e8b.png)

-Yet, after clicking save, the layout will get back to default. (When go to preview, the layout will still be there)

**Comment by kwokwilliam** [comment]
Similar issue to #17. Styling unsupported.
