### ISSUE TITLE
Number List Resets after 9

### ISSUE THREAD

**Issue by charlyecastro** [placeholder-team-name/placeholder#18]
### Steps
1. Click on the number list icon
2. Type something
3. press enter for next line
4. repeat step 2 and step 3

<br>

<img width="1440" alt="Screen Shot 2019-06-10 at 10 12 07 PM" src="https://user-images.githubusercontent.com/24886389/59245312-15b12c00-8bcd-11e9-960e-42c098f39366.png">

**Comment by kwokwilliam** [comment]
We may be unable to fix this if it is a React Draft WYSIWYG issue. More investigation needed to determine this.

**Comment by kwokwilliam** [comment]
They are actually parsed correctly. This is a styling issue. The way it is currently styled uses `left: x px`. This is not under our control easily. We can fix it with simple CSS but only to a certain degree. For example, if we popped it out so three digits worked fine, going to 4+ digits would fail. This style is controlled by React Draft WYSIWYG, so again out of our control.
