### ISSUE TITLE
UI feels tight on larger screens

### ISSUE THREAD

**Issue by navjanar1** [placeholder-team-name/placeholder#22]
UI feels very crunched into small space when on slightly bigger screen (27 iinch screen to be exact), might want to spread things out to make UI look nicer and more user friendly
![Screen Shot 2019-06-11 at 2 22 19 AM](https://user-images.githubusercontent.com/37914670/59260126-e2cc5f80-8bef-11e9-94cf-cc446eb53985.png)

**Comment by vincentmvdm** [comment]
Closing because it is a minor fix that doesn't affect our app's core functionality! Great suggestion and we'll look at it in the future!

**Comment by clairehjk** [comment]
Update: This is not a real failure, but we made changes according to this suggestion:
https://github.com/placeholder-team-name/postcards/pull/38
