### ISSUE TITLE
Enable Push Notifications functionality on Settings page

### ISSUE THREAD

**Issue by navjanar1** [placeholder-team-name/placeholder#23]
1. Click "Recipents" in the top right corner of the page
“Enable Push Notifications” looks like a button, but is not clickable (or is not allowing me to enable push notifications when I initially did not allow push notifications, or if it does, I dont know it is since there is no user feedback)

**Comment by kwokwilliam** [comment]
We show users that they need to enable push notifications in their browser settings in that case: https://www.dropbox.com/s/38061hcf5kdhfyo/Screenshot%202019-06-11%2016.42.59.png?dl=0. The relevant code is here: https://github.com/placeholder-team-name/postcards/blob/development/frontend/src/hooks/usePush.js

**Comment by kwokwilliam** [comment]
Upon inspection, the message fails to appear. Double checking with team where it might be going wrong.

**Comment by vincentmvdm** [comment]
We don't think this bug exists and believe it's the result of a misunderstanding of how the push API works. I'll record a video now walking through our app's push notification and explaining the browser push API. Let us know if after that you still believe something is not working correctly.

**Comment by vincentmvdm** [comment]
We indeed think that this is a misunderstanding and our app has worked correctly all along. Here is an explanation and walkthrough:

https://www.youtube.com/embed/4XB6RbK_YXQ

1. Push notifications have to be enabled in the browser for you to enable/disable them in our app. If you deny the browser's push notifications request our app will tell you "Please enable push notifications in your browser and refresh this page." At that point, our enable button won't do anything as expected. For better UX, we could hide the button all together that but that's a minor UI improvement. This message is visible in another issue reported by you: https://github.com/placeholder-team-name/placeholder/issues/22
2. To be able to enable/disable push notifications in our app, you have to go to your browser settings and allow push notifications per our app's instructions. Once you do that and refresh the page, again per our app's instructions, your push notifications are enabled
3. Our app's enable/disable button now works and you can toggle push notifications on/off. Note how you get this behavior from the start if you press "Allow" when your browser prompts you to enable push notifications

Thanks!
