### ISSUE TITLE
Recipients page layout not user friendly for larger screens

### ISSUE THREAD

**Issue by navjanar1** [placeholder-team-name/placeholder#24]
UI Layout of the “Recipients” page seems odd, with the arrow to view the details of the recipient quite far from the right side information, almost did not notice that it was a button
![Screen Shot 2019-06-11 at 2 32 36 AM](https://user-images.githubusercontent.com/37914670/59260933-6470bd00-8bf1-11e9-92b2-9013994f31de.png)

**Comment by kwokwilliam** [comment]
This is actually the same for all screens. This is just due to the way we styled it.

**Comment by vincentmvdm** [comment]
A bit odd indeed but not an issue that affects core functionality/we have prioritized. Thanks for reporting!
