### ISSUE TITLE
New Recipient

### ISSUE THREAD

**Issue by rioishii** [placeholder-team-name/placeholder#27]
After submitting a new recipient without any information, it tells me the first name and email is required but doesn't allow me to input anything in the textbox. I am not sure if this is intended or not but after accidentally submitting a new recipient without required information, they are locked and have to refresh the page. 

Reproduction steps:
1. Sign in
2. Go to recipients
3. Add recipient
4. Submit without any information

**Comment by clairehjk** [comment]
I haven't been able to reproduce this bug.

**Comment by kwokwilliam** [comment]
This issue might be just a UX issue where you were getting confused at what was the input element. We should style it to make it more clear.

**Comment by kwokwilliam** [comment]
This is not a real failure. It is an UX issue which we made modifications: Added gray border to make clear. Change reflected here: https://github.com/placeholder-team-name/postcards/commit/2fadc8ded7aee780d4c05510149f5c1fed313cc3
