### ISSUE TITLE
design edits

### ISSUE THREAD

**Issue by jinc132** [placeholder-team-name/placeholder#29]
After pressing on the sign up button, i cannot edit the greeting or edit who I am sending the postcard to. It would be great if the postcard had instructions that users are creating the postcard since it gives the perception that it was a sample.

**Comment by kwokwilliam** [comment]
Closing as this is not a real failure. It is a prompt that is not supposed to be able to edited. You can also edit who you're sending the postcard to under Recipients. We never had this in our requirements to be able to do. 
https://github.com/placeholder-team-name/placeholder/blob/master/requirements.md#write-and-preview
