### ISSUE TITLE
Going to a URL that requires authentication when signed out results in a blank page

### ISSUE THREAD

**Issue by jamesbmc** [placeholder-team-name/placeholder#3]
Minor
1. Sign up
2. Sign out
3. Go to https://postcards.netlify.com/recipients/new
4. Blank page with navbar at top

**Comment by kwokwilliam** [comment]
Mess with react router routes in App.js I think to fix

**Comment by kwokwilliam** [comment]
Fixed with recent commit to development
https://github.com/placeholder-team-name/postcards/commit/3cb3aae70719a1d49bb5592cf246f69d5b99ac85
