### ISSUE TITLE
cannot go back to write postcard after pressing on the name

### ISSUE THREAD

**Issue by jinc132** [placeholder-team-name/placeholder#30]
I press on sign up and press the account logo and it switches to the adding a recipients however, I cannot go back to making a postcard. A back button would help.

**Comment by clairehjk** [comment]
You can go back by clicking Postcards on the left nav or hit back on your browser.

**Comment by kwokwilliam** [comment]
This is not a real failure. However we made changes according to this request.
Added explicit go back button in commit: 
https://github.com/placeholder-team-name/postcards/commit/5e8ed58d86e5d45c4e2f2ca129c1f5c2cf64b8f9
