### ISSUE TITLE
Confusing menu bar

### ISSUE THREAD

**Issue by JessicaXLou** [placeholder-team-name/placeholder#31]
![image](https://user-images.githubusercontent.com/32353106/59308012-c4e51600-8c54-11e9-8547-10cfa68528b5.png)
Because my face and the Recipients button is directly next to each other, it makes it look like I am my own recipient, when in fact my face is another button that leads to more functionality.

**Comment by JessicaXLou** [comment]
The screenshot is of the top right corner of the page.

**Comment by kwokwilliam** [comment]
This is not a real failure. However we made changes according to this request. Updated ux to reflect this better in commit: https://github.com/placeholder-team-name/postcards/commit/3c40c53a130ec259e50ef741db8fbfe9420e4aee
