### ISSUE TITLE
Allows me to add myself as a recipient

### ISSUE THREAD

**Issue by JessicaXLou** [placeholder-team-name/placeholder#32]
![image](https://user-images.githubusercontent.com/32353106/59308175-33c26f00-8c55-11e9-9b5c-235fc6482ccf.png)
Allows me to add the same email as my login email as a recipient.

**Comment by clairehjk** [comment]
This is intended behavior and is not a bug. We are marking this as a non-failure!
https://github.com/placeholder-team-name/placeholder/blob/master/requirements.md#recipients
