### ISSUE TITLE
No way to delete a recipient

### ISSUE THREAD

**Issue by JessicaXLou** [placeholder-team-name/placeholder#33]
![image](https://user-images.githubusercontent.com/32353106/59308227-56548800-8c55-11e9-83fb-29e4ab7fcc99.png)
![image](https://user-images.githubusercontent.com/32353106/59308229-594f7880-8c55-11e9-8b0c-1048ace872aa.png)
There's no way to delete a recipient in the recipients page.

**Comment by vincentmvdm** [comment]
Great suggestion! Deleting a recipient was out of scope for this assignment and we intentionally did not implement it because it is not part of our requirements. Thanks for reporting! 
https://github.com/placeholder-team-name/placeholder/blob/master/requirements.md#recipients
