### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by JessicaXLou** [placeholder-team-name/placeholder#34]
![image](https://user-images.githubusercontent.com/32353106/59308436-e5fa3680-8c55-11e9-9bde-9c153f92d621.png)
The phrase "Log in or sign up" implies that there are two different paths a user would take for either log in or sign up. A better phrasing would just be "Sign in with Google"

**Comment by kwokwilliam** [comment]
Fixed, also duplicate see #12
