### ISSUE TITLE
Clicking save adds question marks

### ISSUE THREAD

**Issue by emilytao19** [placeholder-team-name/placeholder#4]
<img width="386" alt="Screen Shot 2019-06-10 at 4 04 27 PM" src="https://user-images.githubusercontent.com/32439428/59233554-d1f2fe00-8b9d-11e9-8446-abb254f228ad.png">

**Comment by emilytao19** [comment]
I added an image to my postcard and clicking save added a question mark near the picture every time

**Comment by kwokwilliam** [comment]
This is an artifact of React-Draft-WYSIWYG that we unfortunately cannot fix within the timeframe because we do not own that code and also it's a huge library.
