### ISSUE TITLE
Navigating away from an existing recipient

### ISSUE THREAD

**Issue by emilytao19** [placeholder-team-name/placeholder#5]
There is no back button after you click on an existing recipient, I would add a back button to the all recipients screen so the user is not stuck on the one recipient. 
<img width="672" alt="Screen Shot 2019-06-10 at 4 41 15 PM" src="https://user-images.githubusercontent.com/32439428/59233803-cfdd6f00-8b9e-11e9-950c-16785ab01519.png">

**Comment by kwokwilliam** [comment]
Added a go back button
