### ISSUE TITLE
Preview does not change on font change

### ISSUE THREAD

**Issue by emilytao19** [placeholder-team-name/placeholder#6]
1. Write some text
2. Change the font of the text, the text changes font
3. Click the preview button
4. The text is the default font even though the font was changed
5. Click the write button
6. The font is again displayed as the changed font
<img width="1177" alt="Screen Shot 2019-06-10 at 5 01 44 PM" src="https://user-images.githubusercontent.com/32439428/59234467-b2f66b00-8ba1-11e9-9738-76de050f3d5c.png">
<img width="648" alt="Screen Shot 2019-06-10 at 5 01 49 PM" src="https://user-images.githubusercontent.com/32439428/59234468-b2f66b00-8ba1-11e9-943e-04f934eea98f.png">

**Comment by kwokwilliam** [comment]
FontFamily was not originally an intended to be supported feature. We have just removed it. I have accidentally let certain feature that we intended to disable through.
