### ISSUE TITLE
Not having a box wrapping the input box

### ISSUE THREAD

**Issue by rheaxychen** [placeholder-team-name/placeholder#8]
![image](https://user-images.githubusercontent.com/24926110/59242032-e398cd80-8bbe-11e9-889b-dbfe0675c382.png)

Steps: having <div> wrapping around the input box for aesthetic improvement.

**Comment by kwokwilliam** [comment]
This is not a real failure. However according to this suggestion we added black border.
Change reflected here: https://github.com/placeholder-team-name/postcards/pull/38
