### ISSUE TITLE
Refreshing the page will lose current edits

### ISSUE THREAD

**Issue by rheaxychen** [placeholder-team-name/placeholder#9]
![Screen Shot 2019-06-10 at 8 34 21 PM](https://user-images.githubusercontent.com/24926110/59242178-6cb00480-8bbf-11e9-8783-e1c1f6481b1a.png)
Figure 1 - before refreshing the page

![image](https://user-images.githubusercontent.com/24926110/59242123-45f1ce00-8bbf-11e9-8cb3-7adb5f436462.png)
Figure 2 - after refreshing the page

**Current edits should be preserved while refreshing the page.**

**Comment by kwokwilliam** [comment]
We never intended to support auto save, there's a save button for a reason. Low priority issue, easily implemented through the use of a timer or a ontabclose function but never was intended.
